### PR TITLE
Chapter 2 code complete

### PR DESCRIPTION
**Pull request by DavidColby**

### CODE REVIEW

**Comment by mediafinger** [comment]
Hey @DavidColby,

first of all let me thank you for making your book available for free. ❤️ 

I started following it, but already run into an `ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.)` issue in Chapter 2: https://book.hotwiringrails.com/chapters/2#build-the-signup-flow

I am aware you don't have the time to keep the book up-to-date, but could you maybe point all your readers to one place / forum to discuss such issues and help each other to solve such issues? Probably it would be easiest to allow "Issues" in this repo, even if you don't moderate them.

> _Even nicer would be to make the source code of book available in a GitHub repo, so the community could keep it updated and correct errors - though I understand if you don't want to give up control over your work._

**Comment by DavidColby** [comment]
Hi @mediafinger — the issue you are experiencing is _likely_ because you do not have a Redis server running locally. Make sure you've got Redis running and you shouldn't see that error moving forward.

For the broader point about where to discuss issues with other book readers, I've added [discussions](https://github.com/DavidColby/hotwired_ats_code/discussions) to this repo as a starting point. I'll add a note to the introduction of the book after work today to point folks there if they have trouble or want to ask questions about the content.

**Comment by mediafinger** [comment]
@DavidColby thanks a lot 😃 

My Redis was running. To make it work I had to add my **Redis password** to the _config/environments/development.rb_ file:

`config.cache_store = :redis_cache_store, { url: ENV.fetch("REDIS_URL", "redis://localhost:6379/1"), password: "redis" }`

Thanks for pointing me in the right direction (as the error message did not help me much).

**Comment by pratiktamang** [comment]
I spent like 3 hours re-doing stuff cause I thought I missed something. I started `redis` and it started working. Didn't need to add password 😄

**Pull request merged**
